/*
 * Timers.c
 *
 *  Created on: Oct 12, 2021
 *      Author: Abdelrhman
 */
#include "Std_DataType.h"
#include "Math.h"
#include "Error.h"
#include "Atmega32A.h"
#include "Timers_Private.h"
#include "Timers_Config.h"
#include "Timers.h"

static void (*GlobalPointer_Timer0_CompareMatchEvent)(void) = NULL;
static void (*GlobalPointer_Timer0_OverFlowEvent)(void) = NULL;
static void (*GlobalPointer_Timer1_OverFlowEvent) (void) = NULL;
static void (*GlobalPointer_Timer1_CompareMatchAEvent) (void) = NULL;
static void (*GlobalPointer_Timer1_CompareMatchBEvent) (void) = NULL;
static void (*GlobalPointer_Timer1_CaptureEvent) (void) = NULL;
static void (*GlobalPointer_Timer2_CompareMatchEvent)(void) = NULL;
static void (*GlobalPointer_Timer2_OverFlowEvent)(void) = NULL;
/**************************************************************************************************************************/
/*******************************************TIMER0**************************************************************************/
/**************************************************************************************************************************/


void Timer0_Initiate(void)
{
	/*Set waveform generation mode, compare output mode and interrupt mode*/
	#if TIMER0_OPERATION_MODE == TIMER0_NORMAL
		CLEAR_BIT(TCCR0_REG,TCCR0_WGM01_BIT);
		CLEAR_BIT(TCCR0_REG,TCCR0_WGM00_BIT);
		#if    TIMER0_COMPARE_OUTPUT_MODE == TIMER0_TOGGLE_OC0_PIN
			CLEAR_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			SET_BIT(TCCR0_REG,TCCR0_COM00_BIT);
			SET_BIT(DDRB_REG,PIN3); /*Set pin as output pin*/
		#elif TIMER0_COMPARE_OUTPUT_MODE == TIMER0_CLEAR_OC0_PIN
			SET_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			CLEAR_BIT(TCCR0_REG,TCCR0_COM00_BIT);
			SET_BIT(DDRB_REG,PIN3); /*Set pin as output pin*/
		#elif TIMER0_COMPARE_OUTPUT_MODE == TIMER0_SET_OC0_PIN
			SET_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			SET_BIT(TCCR0_REG,TCCR0_COM00_BIT);
			SET_BIT(DDRB_REG,PIN3); /*Set pin as output pin*/
		#elif TIMER0_COMPARE_OUTPUT_MODE == TIMER0_DISCONNECT_OC0
			CLEAR_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			CLEAR_BIT(TCCR0_REG,TCCR0_COM00_BIT);
		#else
			#error "Error at TIMER0_COMPARE_OUTPUT_MODE config or selected option isn't suitable for TIMER0_OPERATION_MODE"
		#endif /*TIMER0_COMPARE_OUTPUT_MODE*/
		#if TIMER0_INTERRUPT_ENABLE == TIMER0_ENABLE_INTERRUPT
			SET_BIT(TIMSK_REG,TIMSK_TOIE0_BIT);
		#elif TIMER0_INTERRUPT_ENABLE == TIMER0_DISABLE_INTERRUPT
			CLEAR_BIT(TIMSK_REG,TIMSK_TOIE0_BIT);
		#else
			#error "Error in TIMER0_INTERRUPT_ENABLE config"
		#endif /*TIMER0_INTERRUPT_ENABLE*/
	#elif TIMER0_OPERATION_MODE == TIMER0_PWM_PHASE_CORRECT
		CLEAR_BIT(TCCR0_REG,TCCR0_WGM01_BIT);
		SET_BIT(TCCR0_REG,TCCR0_WGM00_BIT);
		#if     TIMER0_COMPARE_OUTPUT_MODE == TIMER0_CLEAR_OC0_AT_UP_COUNT
			SET_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			CLEAR_BIT(TCCR0_REG,TCCR0_COM00_BIT);
			SET_BIT(DDRB_REG,PIN3); /*Set pin as output pin*/
		#elif  TIMER0_COMPARE_OUTPUT_MODE == TIMER0_SET_OC0_AT_UP_COUNT
			SET_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			SET_BIT(TCCR0_REG,TCCR0_COM00_BIT);
			SET_BIT(DDRB_REG,PIN3); /*Set pin as output pin*/
		#elif  TIMER0_COMPARE_OUTPUT_MODE == TIMER0_DISCONNECT_OC0
			CLEAR_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			CLEAR_BIT(TCCR0_REG,TCCR0_COM00_BIT);
		#else
			#error "Error at TIMER0_COMPARE_OUTPUT_MODE config or selected option isn't suitable for TIMER0_OPERATION_MODE"
		#endif /*TIMER0_COMPARE_OUTPUT_MODE*/

	#elif TIMER0_OPERATION_MODE == TIMER0_CTC
		SET_BIT(TCCR0_REG,TCCR0_WGM01_BIT);
		CLEAR_BIT(TCCR0_REG,TCCR0_WGM00_BIT);
		#if    TIMER0_COMPARE_OUTPUT_MODE == TIMER0_TOGGLE_OC0_PIN
			CLEAR_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			SET_BIT(TCCR0_REG,TCCR0_COM00_BIT);
			SET_BIT(DDRB_REG,PIN3); /*Set pin as output pin*/
		#elif TIMER0_COMPARE_OUTPUT_MODE == TIMER0_CLEAR_OC0_PIN
			SET_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			CLEAR_BIT(TCCR0_REG,TCCR0_COM00_BIT);
			SET_BIT(DDRB_REG,PIN3); /*Set pin as output pin*/
		#elif TIMER0_COMPARE_OUTPUT_MODE == TIMER0_SET_OC0_PIN
			SET_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			SET_BIT(TCCR0_REG,TCCR0_COM00_BIT);
			SET_BIT(DDRB_REG,PIN3); /*Set pin as output pin*/
		#elif TIMER0_COMPARE_OUTPUT_MODE == TIMER0_DISCONNECT_OC0
			CLEAR_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			CLEAR_BIT(TCCR0_REG,TCCR0_COM00_BIT);
		#else
			#error "Error at TIMER0_COMPARE_OUTPUT_MODE config or selected option isn't suitable for TIMER0_OPERATION_MODE"
		#endif /*TIMER0_COMPARE_OUTPUT_MODE*/
		#if TIMER0_INTERRUPT_ENABLE == TIMER0_ENABLE_INTERRUPT
			SET_BIT(TIMSK_REG,TIMSK_OCIE0_BIT);
		#elif TIMER0_INTERRUPT_ENABLE == TIMER0_DISABLE_INTERRUPT
			CLEAR_BIT(TIMSK_REG,TIMSK_OCIE0_BIT);
		#else
			#error "Error in TIMER0_INTERRUPT_ENABLE config"
		#endif /*TIMER0_INTERRUPT_ENABLE*/
	#elif TIMER0_OPERATION_MODE == TIMER0_FAST_PWM
		SET_BIT(TCCR0_REG,TCCR0_WGM01_BIT);
		SET_BIT(TCCR0_REG,TCCR0_WGM00_BIT);
		#if     TIMER0_COMPARE_OUTPUT_MODE == TIMER0_NON_INVERTING_MODE
			SET_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			CLEAR_BIT(TCCR0_REG,TCCR0_COM00_BIT);
			SET_BIT(DDRB_REG,PIN3); /*Set pin as output pin*/
		#elif  TIMER0_COMPARE_OUTPUT_MODE == TIMER0_INVERTING_MODE
			SET_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			SET_BIT(TCCR0_REG,TCCR0_COM00_BIT);
			SET_BIT(DDRB_REG,PIN3); /*Set pin as output pin*/
		#elif  TIMER0_COMPARE_OUTPUT_MODE == TIMER0_DISCONNECT_OC0
			CLEAR_BIT(TCCR0_REG,TCCR0_COM01_BIT);
			CLEAR_BIT(TCCR0_REG,TCCR0_COM00_BIT);
		#else
			#error "Error at TIMER0_COMPARE_OUTPUT_MODE config or selected option isn't suitable for TIMER0_OPERATION_MODE"
		#endif /*TIMER0_COMPARE_OUTPUT_MODE*/
	#else
		#error "Error at TIMER0_OPERATION_MODE config"
	#endif /*TIMER0_OPERATION_MODE*/

	/*Set Timer frequency*/
	#if TIMER0_FREQUENCY == TIMER0_FOSC
		CLEAR_BIT(TCCR0_REG,TCCR0_CS02_BIT);
		CLEAR_BIT(TCCR0_REG,TCCR0_CS01_BIT);
		SET_BIT(TCCR0_REG,TCCR0_CS00_BIT);
	#elif TIMER0_FREQUENCY == TIMER0_FOSC_OVER_8
		CLEAR_BIT(TCCR0_REG,TCCR0_CS02_BIT);
		SET_BIT(TCCR0_REG,TCCR0_CS01_BIT);
		CLEAR_BIT(TCCR0_REG,TCCR0_CS00_BIT);
	#elif TIMER0_FREQUENCY == TIMER0_FOSC_OVER_64
		CLEAR_BIT(TCCR0_REG,TCCR0_CS02_BIT);
		SET_BIT(TCCR0_REG,TCCR0_CS01_BIT);
		SET_BIT(TCCR0_REG,TCCR0_CS00_BIT);
	#elif TIMER0_FREQUENCY == TIMER0_FOSC_OVER_256
		SET_BIT(TCCR0_REG,TCCR0_CS02_BIT);
		CLEAR_BIT(TCCR0_REG,TCCR0_CS01_BIT);
		CLEAR_BIT(TCCR0_REG,TCCR0_CS00_BIT);
	#elif TIMER0_FREQUENCY == TIMER0_FOSC_OVER_1024
		SET_BIT(TCCR0_REG,TCCR0_CS02_BIT);
		CLEAR_BIT(TCCR0_REG,TCCR0_CS01_BIT);
		SET_BIT(TCCR0_REG,TCCR0_CS00_BIT);
	#elif TIMER0_FREQUENCY == TIMER0_EXTERNAL_CLK_FALLING
		SET_BIT(TCCR0_REG,TCCR0_CS02_BIT);
		SET_BIT(TCCR0_REG,TCCR0_CS01_BIT);
		CLEAR_BIT(TCCR0_REG,TCCR0_CS00_BIT);
	#elif TIMER0_FREQUENCY == TIMER0_EXTERNAL_CLK_RISING
		SET_BIT(TCCR0_REG,TCCR0_CS02_BIT);
		SET_BIT(TCCR0_REG,TCCR0_CS01_BIT);
		SET_BIT(TCCR0_REG,TCCR0_CS00_BIT);
	#else
		#error "Error in TIMER0_FREQUENCY config"
	#endif /*TIMER0_FREQUENCY*/


}
void Timer0_Disable(void)
{
	CLEAR_BIT(TCCR0_REG,TCCR0_CS02_BIT);
	CLEAR_BIT(TCCR0_REG,TCCR0_CS01_BIT);
	CLEAR_BIT(TCCR0_REG,TCCR0_CS00_BIT);
}

void Timer0_SetPreLoadValue(uint8 PreLoadVal)
{
	TCNT0_REG = PreLoadVal;
}

void Timer0_SetCompareMatchValue(uint8 CompareMatchVal)
{
	OCR0_REG = CompareMatchVal;
}
Error_t Timer0_SetCallBackFunctionCompareMatch(void (*Timer0_CompareMatchIsr) (void))
{
	Error_t ReturnedError = NoError;
	if(Timer0_CompareMatchIsr != NULL)
	{
		/*Set global pointer to Isr function*/
		GlobalPointer_Timer0_CompareMatchEvent = Timer0_CompareMatchIsr;
		/*Set timer interrupt*/

	}
	else
	{
		ReturnedError = NullPointer;
	}
	return ReturnedError;
}
Error_t Timer0_SetCallBackFunctionOverFlow(void (*Timer0_OVERFLOWIsr) (void))
{
	Error_t ReturnedError = NoError;
	if(Timer0_OVERFLOWIsr != NULL)
	{
		/*Set global pointer to Isr function*/
		GlobalPointer_Timer0_OverFlowEvent = Timer0_OVERFLOWIsr;

	}
	else
	{
		ReturnedError = NullPointer;
	}
	return ReturnedError;
}

void Timer0_PWM_OC0Pin(uint8 CompareMatchValue)
{
	OCR0_REG = CompareMatchValue;
}

/* ISR Function for Timer0 OverFlow event */
void __vector_11(void)  __attribute__((signal));
void __vector_11(void)
{
	if(GlobalPointer_Timer0_OverFlowEvent != NULL)
	{
		GlobalPointer_Timer0_OverFlowEvent();
	}
}

/* ISR Function for Timer0 ComapreMatch event */
void __vector_10(void)  __attribute__((signal));
void __vector_10(void)
{
	if(GlobalPointer_Timer0_CompareMatchEvent != NULL)
	{
		GlobalPointer_Timer0_CompareMatchEvent();
	}
}

/**************************************************************************************************************************/
/*******************************************TIMER1**************************************************************************/
/**************************************************************************************************************************/
void Timer1_Initiate(void)
{
	/*Set compare output mode, Wave generation mode,*/
	/*For PWM modes*/
	#if (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_8BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_9BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_10BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_8BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_9BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_10BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_TOP_ICR1) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_TOP_OCR1A) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_FREQUENCY_CORRECT_TOP_ICR1) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_FREQUENCY_CORRECT_TOP_OCR1A) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_TOP_OCR1A) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_TOP_ICR1)
		/*Fast PWM modes*/
		#if  (TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_8BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_9BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_10BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_TOP_ICR1) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_TOP_OCR1A)

			#if TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_8BITS
				/*Activate mode*/
				SET_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_9BITS
				/*Activate mode*/
				CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_10BITS
				/*Activate mode*/
				SET_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_TOP_ICR1
				/*Activate mode*/
				CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_FAST_PWM_TOP_OCR1A
				/*Activate mode*/
				SET_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#endif /*TIMER1_WAVE_GENERATION_MODE*/
			#if TIMER1_COMPARE_OUTPUT_MODE_OC1A == TIMER1_NON_INVERTING_MODE_OC1A
				SET_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
				SET_BIT(DDRD_REG,PIN5);
			#elif TIMER1_COMPARE_OUTPUT_MODE_OC1A == TIMER1_INVERTING_MODE_OC1A
				SET_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
				SET_BIT(DDRD_REG,PIN5);
			#elif TIMER1_COMPARE_OUTPUT_MODE_OC1A == TIMER1_DISCONNECT_OC1A
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
				SET_BIT(DDRD_REG,PIN5);
			#else
				#error "Error in TIMER1_COMPARE_OUTPUT_MODE_OC1A config"
			#endif /*TIMER1_COMPARE_OUTPUT_MODE_OC1A*/
			#if TIMER1_COMPARE_OUTPUT_MODE_OC1B == TIMER1_NON_INVERTING_MODE_OC1B
				SET_BIT(TCCR1A_REG,TCCR1A_COM1B1_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1B0_BIT);
				SET_BIT(DDRD_REG,PIN4);
			#elif TIMER1_COMPARE_OUTPUT_MODE_OC1B == TIMER1_INVERTING_MODE_OC1B
				SET_BIT(TCCR1A_REG,TCCR1A_COM1B1_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_COM1B0_BIT);
				SET_BIT(DDRD_REG,PIN4);
			#elif TIMER1_COMPARE_OUTPUT_MODE_OC1B == TIMER1_DISCONNECT_OC1B
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1B1_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1B0_BIT);
				SET_BIT(DDRD_REG,PIN4);
			#else
				#error "Error in TIMER1_COMPARE_OUTPUT_MODE_OC1B config"
			#endif /*TIMER1_COMPARE_OUTPUT_MODE_OC1B*/
		/*Phase correct modes*/
		#elif  (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_8BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_9BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_10BITS) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_FREQUENCY_CORRECT_TOP_ICR1) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_FREQUENCY_CORRECT_TOP_OCR1A) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_TOP_OCR1A) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_TOP_ICR1)

			#if TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_8BITS
				/*Activate mode*/
				SET_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_9BITS
				/*Activate mode*/
				CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_10BITS
				/*Activate mode*/
				SET_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_FREQUENCY_CORRECT_TOP_ICR1
				/*Activate mode*/
				CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_FREQUENCY_CORRECT_TOP_OCR1A
				/*Activate mode*/
				SET_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_TOP_ICR1
				/*Activate mode*/
				CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#elif TIMER1_WAVE_GENERATION_MODE == TIMER1_PHASE_CORRECT_TOP_OCR1A
				/*Activate mode*/
				SET_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
				CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
				SET_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			#endif/*TIMER1_WAVE_GENERATION_MODE*/
			#if TIMER1_COMPARE_OUTPUT_MODE_OC1A == TIMER1_CLEAR_OC1A_AT_UP_COUNT
				SET_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
			#elif TIMER1_COMPARE_OUTPUT_MODE_OC1A == TIMER1_SET_OC1A_AT_UP_COUNT
				SET_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
			#elif TIMER1_COMPARE_OUTPUT_MODE_OC1A == TIMER1_DISCONNECT_OC1A
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
			#endif /*TIMER1_COMPARE_OUTPUT_MODE_OC1A*/
			#if TIMER1_COMPARE_OUTPUT_MODE_OC1B == TIMER1_CLEAR_OC1B_AT_UP_COUNT
				SET_BIT(TCCR1A_REG,TCCR1A_COM1B1_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1B0_BIT);
			#elif TIMER1_COMPARE_OUTPUT_MODE_OC1B == TIMER1_SET_OC1B_AT_UP_COUNT
				SET_BIT(TCCR1A_REG,TCCR1A_COM1B1_BIT);
				SET_BIT(TCCR1A_REG,TCCR1A_COM1B0_BIT);
			#elif TIMER1_COMPARE_OUTPUT_MODE_OC1B == TIMER1_DISCONNECT_OC1B
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1B1_BIT);
				CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1B0_BIT);
			#endif /*TIMER1_COMPARE_OUTPUT_MODE_OC1B*/
		#endif /*PWM modes*/
	/*For non pwm modes*/
	#elif (TIMER1_WAVE_GENERATION_MODE == TIMER1_NORMAL) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_CTC_TOP_OCR1A) || (TIMER1_WAVE_GENERATION_MODE == TIMER1_CTC_TOP_ICR1)

		#if (TIMER1_WAVE_GENERATION_MODE == TIMER1_NORMAL)
			/*Activate mode*/
			CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
			CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
			CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
			CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			/*Interrupt mode*/
			#if TIMER1_INTERRUPT_ENABLE == TIMER1_ENABLE_INTERRUPT
			SET_BIT(TIMSK_REG,TIMSK_TOIE1_BIT);
			#elif TIMER1_INTERRUPT_ENABLE == TIMER1_DISABLE_INTERRUPT
			CLEAR_BIT(TIMSK_REG,TIMSK_TOIE1_BIT);
			#endif /*TIMER1_INTERRUPT_ENABLE*/
		#elif  (TIMER1_WAVE_GENERATION_MODE == TIMER1_CTC_TOP_OCR1A)
			/*Activate mode*/
			CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
			CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
			SET_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
			CLEAR_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			/*Interrupt enable*/
			#if TIMER1_INTERRUPT_ENABLE	== TIMER1_ENABLE_INTERRUPT
				SET_BIT(TIMSK_REG,TIMSK_OCIE1A_BIT);
			#elif TIMER1_INTERRUPT_ENABLE == TIMER1_DISABLE_INTERRUPT
				CLEAR_BIT(TIMSK_REG,TIMSK_OCIE1A_BIT);
			#endif /*TIMER1_INTERRUPT_ENABLE*/
			#if TIMER1_INTERRUPT_ENABLE	== TIMER1_ENABLE_INTERRUPT
				SET_BIT(TIMSK_REG,TIMSK_OCIE1B_BIT);
			#elif TIMER1_INTERRUPT_ENABLE == TIMER1_DISABLE_INTERRUPT
				CLEAR_BIT(TIMSK_REG,TIMSK_OCIE1B_BIT);
			#endif /*TIMER1_INTERRUPT_ENABLE*/
		#elif (TIMER1_WAVE_GENERATION_MODE == TIMER1_CTC_TOP_ICR1)
			/*Activate mode*/
			CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM10_BIT);
			CLEAR_BIT(TCCR1A_REG,TCCR1A_WGM11_BIT);
			SET_BIT(TCCR1B_REG,TCCR1B_WGM12_BIT);
			SET_BIT(TCCR1B_REG,TCCR1B_WGM13_BIT);
			/*interrupt mode*/
			#if TIMER1_INTERRUPT_ENABLE == TIMER1_ENABLE_INTERRUPT
			SET_BIT(TIMSK_REG,TIMSK_OCIE1A_BIT);
			SET_BIT(TIMSK_REG,TIMSK_OCIE1B_BIT);
			#elif TIMER1_INTERRUPT_ENABLE == TIMER1_DISABLE_INTERRUPT
			CLEAR_BIT(TIMSK_REG,TIMSK_OCIE1A_BIT);
			CLEAR_BIT(TIMSK_REG,TIMSK_OCIE1B_BIT);
			#endif /*TIMER1_INTERRUPT_ENABLE*/
		#endif /*TIMER1_WAVE_GENERATION_MODE*/

		/*Set compare match output mode*/
		#if TIMER1_COMPARE_OUTPUT_MODE_OC1A == TIMER1_TOGGLE_OC1A_PIN
			CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
			SET_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
		#elif TIMER1_COMPARE_OUTPUT_MODE_OC1A == TIMER1_CLEAR_OC1A_PIN
			SET_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
			CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
		#elif TIMER1_COMPARE_OUTPUT_MODE_OC1A == TIMER1_SET_OC1A_PIN
			SET_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
			SET_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
		#elif TIMER1_COMPARE_OUTPUT_MODE_OC1A == TIMER1_DISCONNECT_OC1A
			CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
			CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
		#else
				#error "Not in non pwm mode config"
		#endif /*TIMER1_COMPARE_OUTPUT_MODE_OC1A*/
	#else
		#error "Error in TIMER1_WAVE_GENERATION_MODE config"
	#endif /*TIMER1_WAVE_GENERATION_MODE*/

	/*Set timer frequency*/
	#if TIMER1_FREQUENCY == TIMER1_FOSC
		CLEAR_BIT(TCCR1B_REG,TCCR1B_CS12_BIT);
		CLEAR_BIT(TCCR1B_REG,TCCR1B_CS11_BIT);
		SET_BIT(TCCR1B_REG,TCCR1B_CS10_BIT);
	#elif TIMER1_FREQUENCY == TIMER1_FOSC_OVER_8
		CLEAR_BIT(TCCR1B_REG,TCCR1B_CS12_BIT);
		SET_BIT(TCCR1B_REG,TCCR1B_CS11_BIT);
		CLEAR_BIT(TCCR1B_REG,TCCR1B_CS10_BIT);
	#elif TIMER1_FREQUENCY == TIMER1_FOSC_OVER_64
		CLEAR_BIT(TCCR1B_REG,TCCR1B_CS12_BIT);
		SET_BIT(TCCR1B_REG,TCCR1B_CS11_BIT);
		SET_BIT(TCCR1B_REG,TCCR1B_CS10_BIT);
	#elif TIMER1_FREQUENCY == TIMER1_FOSC_OVER_256
		SET_BIT(TCCR1B_REG,TCCR1B_CS12_BIT);
		CLEAR_BIT(TCCR1B_REG,TCCR1B_CS11_BIT);
		CLEAR_BIT(TCCR1B_REG,TCCR1B_CS10_BIT);
	#elif TIMER1_FREQUENCY == TIMER1_FOSC_OVER_1024
		SET_BIT(TCCR1B_REG,TCCR1B_CS12_BIT);
		CLEAR_BIT(TCCR1B_REG,TCCR1B_CS11_BIT);
		SET_BIT(TCCR1B_REG,TCCR1B_CS10_BIT);
	#elif TIMER1_FREQUENCY == TIMER1_EXTERNAL_CLK_FALLING
		SET_BIT(TCCR1B_REG,TCCR1B_CS12_BIT);
		SET_BIT(TCCR1B_REG,TCCR1B_CS11_BIT);
		CLEAR_BIT(TCCR1B_REG,TCCR1B_CS10_BIT);
	#elif TIMER1_FREQUENCY == TIMER1_EXTERNAL_CLK_RISING
		SET_BIT(TCCR1B_REG,TCCR1B_CS12_BIT);
		SET_BIT(TCCR1B_REG,TCCR1B_CS11_BIT);
		SET_BIT(TCCR1B_REG,TCCR1B_CS10_BIT);
	#else
		  #error "Error in TIMER1_FREQUENCY config"
	#endif /*TIMER1_FREQUENCY*/


}
void Timer1_DisableTimer(void)
{
	CLEAR_BIT(TCCR1B_REG,TCCR1B_CS12_BIT);
	CLEAR_BIT(TCCR1B_REG,TCCR1B_CS11_BIT);
	CLEAR_BIT(TCCR1B_REG,TCCR1B_CS10_BIT);
}
void Timer1_SetPreLoadValue(uint16 Value)
{
	/*HIGH BYTE MUST BE WRITTEN FIRST!!*/
	TCNT1H_REG = Value >> 8;
	TCNT1L_REG = (uint8) Value;
}
void Timer1_SetCompareMatchAValue(uint16 value)
{
	/*HIGH BYTE MUST BE WRITTEN FIRST!!*/
	OCR1AH_REG = value >> 8;
	OCR1AL_REG = (uint8) value;
}

void Timer1_SetCompareMatchBValue(uint16 value)
{
	/*HIGH BYTE MUST BE WRITTEN FIRST!!*/
	OCR1BH_REG = value >> 8;
	OCR1BL_REG = (uint8) value;
}
void Timer1_SetICRValue(uint16 Value)
{
	ICR1H_REG = Value >> 8;
	ICR1L_REG = (uint8) Value;
}

void Timer1_PWM_OC1APin(uint16 CompareMatchAValue)
{
	/*Set the value*/
	OCR1AH_REG = CompareMatchAValue >> 8;
	OCR1AL_REG = (uint8) CompareMatchAValue;
}
void Timer1_PWM_OC1BPin(uint16 CompareMatchBValue)
{
	/*Set the value*/
	OCR1BH_REG = CompareMatchBValue >> 8;
	OCR1BL_REG = (uint8) CompareMatchBValue;
}
void Timer1_SetCallBackFunctionOverFlow(void (*Timer1_OVERFLOWIsr) (void))
{
	if(Timer1_OVERFLOWIsr != NULL)
	{
		GlobalPointer_Timer1_OverFlowEvent = Timer1_OVERFLOWIsr;
	}
}
void Timer1_SetCallBackFunctionCompareMatchA(void (*Timer1_CompareMatch_AIsr) (void))
{
	if(Timer1_CompareMatch_AIsr != NULL)
	{
		GlobalPointer_Timer1_CompareMatchAEvent = Timer1_CompareMatch_AIsr;
	}
}
void Timer1_SetCallBackFunctionCompareMatchB(void (*Timer1_CompareMatch_BIsr) (void))
{
	if(Timer1_CompareMatch_BIsr != NULL)
	{
		GlobalPointer_Timer1_CompareMatchBEvent = Timer1_CompareMatch_BIsr;
	}
}
void Timer1_SetCallBackFunctionCaptureEvent(void (*Timer1_CaptureEventIsr) (void))
{
	if(Timer1_CaptureEventIsr != NULL)
	{
		GlobalPointer_Timer1_CaptureEvent = Timer1_CaptureEventIsr;
	}
}
/* ISR Function for Timer1 overflow event */
void __vector_9(void)  __attribute__((signal));
void __vector_9(void)
{
	if(GlobalPointer_Timer1_OverFlowEvent != NULL)
	{
		GlobalPointer_Timer1_OverFlowEvent();
	}
}

/* ISR Function for Timer1 ComapreMatch-B event */
void __vector_8(void)  __attribute__((signal));
void __vector_8(void)
{
	if(GlobalPointer_Timer1_CompareMatchBEvent != NULL)
	{
		GlobalPointer_Timer1_CompareMatchBEvent();
	}
}

/* ISR Function for Timer1 ComapreMatch-A event */
void __vector_7(void)  __attribute__((signal));
void __vector_7(void)
{
	if(GlobalPointer_Timer1_CompareMatchAEvent != NULL)
	{
		GlobalPointer_Timer1_CompareMatchAEvent();
	}
}
/* ISR Function for Timer1 Capture event */
void __vector_6(void)  __attribute__((signal));
void __vector_6(void)
{
	if(GlobalPointer_Timer1_CaptureEvent != NULL)
	{
		GlobalPointer_Timer1_CaptureEvent();
	}
}
/**************************************************************************************************************************/
/*******************************************TIMER2**************************************************************************/
/**************************************************************************************************************************/

void Timer2_Initiate(void)
{
	/*Set waveform generation mode, compare output mode and interrupt mode*/
	#if TIMER2_OPERATION_MODE == TIMER2_NORMAL
		CLEAR_BIT(TCCR2_REG,TCCR2_WGM21_BIT);
		CLEAR_BIT(TCCR2_REG,TCCR2_WGM20_BIT);
		#if    TIMER2_COMPARE_OUTPUT_MODE == TIMER2_TOGGLE_OC2_PIN
			CLEAR_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			SET_BIT(TCCR2_REG,TCCR2_COM20_BIT);
			SET_BIT(DDRD_REG,PIN7); /*Set pin as output pin*/
		#elif TIMER2_COMPARE_OUTPUT_MODE == TIMER2_CLEAR_OC2_PIN
			SET_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			CLEAR_BIT(TCCR2_REG,TCCR2_COM20_BIT);
			SET_BIT(DDRD_REG,PIN7); /*Set pin as output pin*/
		#elif TIMER2_COMPARE_OUTPUT_MODE == TIMER2_SET_OC2_PIN
			SET_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			SET_BIT(TCCR2_REG,TCCR2_COM20_BIT);
			SET_BIT(DDRD_REG,PIN7); /*Set pin as output pin*/
		#elif TIMER2_COMPARE_OUTPUT_MODE == TIMER2_DISCONNECT_OC2
			CLEAR_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			CLEAR_BIT(TCCR2_REG,TCCR2_COM20_BIT);
		#else
			#error "Error at TIMER2_COMPARE_OUTPUT_MODE config or selected option isn't suitable for TIMER2_OPERATION_MODE"
		#endif /*TIMER2_COMPARE_OUTPUT_MODE*/
		#if TIMER2_INTERRUPT_ENABLE == TIMER2_ENABLE_INTERRUPT
			SET_BIT(TIMSK_REG,TIMSK_TOIE2_BIT);
		#elif TIMER2_INTERRUPT_ENABLE == TIMER2_DISABLE_INTERRUPT
			CLEAR_BIT(TIMSK_REG,TIMSK_TOIE2_BIT);
		#else
			#error "Error in TIMER2_INTERRUPT_ENABLE config"
		#endif /*TIMER2_INTERRUPT_ENABLE*/
	#elif TIMER2_OPERATION_MODE == TIMER2_PWM_PHASE_CORRECT
		CLEAR_BIT(TCCR2_REG,TCCR2_WGM21_BIT);
		SET_BIT(TCCR2_REG,TCCR2_WGM20_BIT);
		#if     TIMER2_COMPARE_OUTPUT_MODE == TIMER2_CLEAR_OC2_AT_UP_COUNT
			SET_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			CLEAR_BIT(TCCR2_REG,TCCR2_COM20_BIT);
			SET_BIT(DDRD_REG,PIN7); /*Set pin as output pin*/
		#elif  TIMER2_COMPARE_OUTPUT_MODE == TIMER2_SET_OC2_AT_UP_COUNT
			SET_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			SET_BIT(TCCR2_REG,TCCR2_COM20_BIT);
			SET_BIT(DDRD_REG,PIN7); /*Set pin as output pin*/
		#elif  TIMER2_COMPARE_OUTPUT_MODE == TIMER2_DISCONNECT_OC2
			CLEAR_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			CLEAR_BIT(TCCR2_REG,TCCR2_COM20_BIT);
		#else
			#error "Error at TIMER2_COMPARE_OUTPUT_MODE config or selected option isn't suitable for TIMER2_OPERATION_MODE"
		#endif /*TIMER2_COMPARE_OUTPUT_MODE*/

	#elif TIMER2_OPERATION_MODE == TIMER2_CTC
		SET_BIT(TCCR2_REG,TCCR2_WGM21_BIT);
		CLEAR_BIT(TCCR2_REG,TCCR2_WGM20_BIT);
		#if    TIMER2_COMPARE_OUTPUT_MODE == TIMER2_TOGGLE_OC2_PIN
			CLEAR_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			SET_BIT(TCCR2_REG,TCCR2_COM20_BIT);
			SET_BIT(DDRD_REG,PIN7); /*Set pin as output pin*/
		#elif TIMER2_COMPARE_OUTPUT_MODE == TIMER2_CLEAR_OC2_PIN
			SET_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			CLEAR_BIT(TCCR2_REG,TCCR2_COM20_BIT);
			SET_BIT(DDRD_REG,PIN7); /*Set pin as output pin*/
		#elif TIMER2_COMPARE_OUTPUT_MODE == TIMER2_SET_OC2_PIN
			SET_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			SET_BIT(TCCR2_REG,TCCR2_COM20_BIT);
			SET_BIT(DDRD_REG,PIN7); /*Set pin as output pin*/
		#elif TIMER2_COMPARE_OUTPUT_MODE == TIMER2_DISCONNECT_OC2
			CLEAR_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			CLEAR_BIT(TCCR2_REG,TCCR2_COM20_BIT);
		#else
			#error "Error at TIMER2_COMPARE_OUTPUT_MODE config or selected option isn't suitable for TIMER2_OPERATION_MODE"
		#endif /*TIMER2_COMPARE_OUTPUT_MODE*/
		#if TIMER2_INTERRUPT_ENABLE == TIMER2_ENABLE_INTERRUPT
			SET_BIT(TIMSK_REG,TIMSK_OCIE2_BIT);
		#elif TIMER2_INTERRUPT_ENABLE == TIMER2_DISABLE_INTERRUPT
			CLEAR_BIT(TIMSK_REG,TIMSK_OCIE2_BIT);
		#else
			#error "Error in TIMER2_INTERRUPT_ENABLE config"
		#endif /*TIMER2_INTERRUPT_ENABLE*/
	#elif TIMER2_OPERATION_MODE == TIMER2_FAST_PWM
		SET_BIT(TCCR2_REG,TCCR2_WGM21_BIT);
		SET_BIT(TCCR2_REG,TCCR2_WGM20_BIT);
		#if     TIMER2_COMPARE_OUTPUT_MODE == TIMER2_NON_INVERTING_MODE
			SET_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			CLEAR_BIT(TCCR2_REG,TCCR2_COM20_BIT);
			SET_BIT(DDRD_REG,PIN7); /*Set pin as output pin*/
		#elif  TIMER2_COMPARE_OUTPUT_MODE == TIMER2_INVERTING_MODE
			SET_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			SET_BIT(TCCR2_REG,TCCR2_COM20_BIT);
			SET_BIT(DDRD_REG,PIN7); /*Set pin as output pin*/
		#elif  TIMER2_COMPARE_OUTPUT_MODE == TIMER2_DISCONNECT_OC2
			CLEAR_BIT(TCCR2_REG,TCCR2_COM21_BIT);
			CLEAR_BIT(TCCR2_REG,TCCR2_COM20_BIT);
		#else
			#error "Error at TIMER2_COMPARE_OUTPUT_MODE config or selected option isn't suitable for TIMER2_OPERATION_MODE"
		#endif /*TIMER2_COMPARE_OUTPUT_MODE*/
	#else
		#error "Error at TIMER2_OPERATION_MODE config"
	#endif /*TIMER2_OPERATION_MODE*/

	/*Set Timer frequency*/
	#if TIMER2_FREQUENCY == TIMER2_FOSC
		CLEAR_BIT(TCCR2_REG,TCCR2_CS22_BIT);
		CLEAR_BIT(TCCR2_REG,TCCR2_CS21_BIT);
		SET_BIT(TCCR2_REG,TCCR2_CS20_BIT);
	#elif TIMER2_FREQUENCY == TIMER2_FOSC_OVER_8
		CLEAR_BIT(TCCR2_REG,TCCR2_CS22_BIT);
		SET_BIT(TCCR2_REG,TCCR2_CS21_BIT);
		CLEAR_BIT(TCCR2_REG,TCCR2_CS20_BIT);
	#elif TIMER2_FREQUENCY == TIMER2_FOSC_OVER_64
		CLEAR_BIT(TCCR2_REG,TCCR2_CS22_BIT);
		SET_BIT(TCCR2_REG,TCCR2_CS21_BIT);
		SET_BIT(TCCR2_REG,TCCR2_CS20_BIT);
	#elif TIMER2_FREQUENCY == TIMER2_FOSC_OVER_256
		SET_BIT(TCCR2_REG,TCCR2_CS22_BIT);
		CLEAR_BIT(TCCR2_REG,TCCR2_CS21_BIT);
		CLEAR_BIT(TCCR2_REG,TCCR2_CS20_BIT);
	#elif TIMER2_FREQUENCY == TIMER2_FOSC_OVER_1024
		SET_BIT(TCCR2_REG,TCCR2_CS22_BIT);
		CLEAR_BIT(TCCR2_REG,TCCR2_CS21_BIT);
		SET_BIT(TCCR2_REG,TCCR2_CS20_BIT);
	#elif TIMER2_FREQUENCY == TIMER2_EXTERNAL_CLK_FALLING
		SET_BIT(TCCR2_REG,TCCR2_CS22_BIT);
		SET_BIT(TCCR2_REG,TCCR2_CS21_BIT);
		CLEAR_BIT(TCCR2_REG,TCCR2_CS20_BIT);
	#elif TIMER2_FREQUENCY == TIMER2_EXTERNAL_CLK_RISING
		SET_BIT(TCCR2_REG,TCCR2_CS22_BIT);
		SET_BIT(TCCR2_REG,TCCR2_CS21_BIT);
		SET_BIT(TCCR2_REG,TCCR2_CS20_BIT);
	#else
		#error "Error in TIMER2_FREQUENCY config"
	#endif /*TIMER2_FREQUENCY*/


}
void Timer2_Disable(void)
{
	CLEAR_BIT(TCCR2_REG,TCCR2_CS22_BIT);
	CLEAR_BIT(TCCR2_REG,TCCR2_CS21_BIT);
	CLEAR_BIT(TCCR2_REG,TCCR2_CS20_BIT);
}

void Timer2_SetPreLoadValue(uint8 PreLoadVal)
{
	TCNT2_REG = PreLoadVal;
}

void Timer2_SetCompareMatchValue(uint8 CompareMatchVal)
{
	OCR2_REG = CompareMatchVal;
}
Error_t Timer2_SetCallBackFunctionCompareMatch(void (*TIMER2_CompareMatchIsr) (void))
{
	Error_t ReturnedError = NoError;
	if(TIMER2_CompareMatchIsr != NULL)
	{
		/*Set global pointer to Isr function*/
		GlobalPointer_Timer2_CompareMatchEvent = TIMER2_CompareMatchIsr;
		/*Set timer interrupt*/

	}
	else
	{
		ReturnedError = NullPointer;
	}
	return ReturnedError;
}
Error_t Timer2_SetCallBackFunctionOverFlow(void (*TIMER2_OVERFLOWIsr) (void))
{
	Error_t ReturnedError = NoError;
	if(TIMER2_OVERFLOWIsr != NULL)
	{
		/*Set global pointer to Isr function*/
		GlobalPointer_Timer2_OverFlowEvent = TIMER2_OVERFLOWIsr;

	}
	else
	{
		ReturnedError = NullPointer;
	}
	return ReturnedError;
}

void Timer2_PWM_OC2Pin(uint8 CompareMatchValue)
{
	OCR2_REG = CompareMatchValue;
}

/* ISR Function for Timer2 OverFlow event */
void __vector_5(void)  __attribute__((signal));
void __vector_5(void)
{
	if(GlobalPointer_Timer2_OverFlowEvent != NULL)
	{
		GlobalPointer_Timer2_OverFlowEvent();
	}
}

/* ISR Function for Timer2 ComapreMatch event */
void __vector_4(void)  __attribute__((signal));
void __vector_4(void)
{
	if(GlobalPointer_Timer2_CompareMatchEvent != NULL)
	{
		GlobalPointer_Timer2_CompareMatchEvent();
	}
}

void Timer_PWM(uint8 Port, uint8 Pin , uint16 Value)
{
	if(Port == OC0_PORT && Pin == OC0_PIN)
	{
		Timer0_PWM_OC0Pin((uint8) Value);
	}
	else if(Port == OC1A_PORT && Pin == OC1A_PIN)
	{
		Timer1_PWM_OC1APin(Value);
	}
	else if(Port == OC1B_PORT && Pin == OC1B_PIN)
	{
		Timer1_PWM_OC1BPin(Value);
	}
	else if(Port == OC2_PORT && Pin == OC2_PIN)
	{
		Timer2_PWM_OC2Pin((uint8) Value);
	}
	else /*Software PWM*/
	{
		
	}
	
}

void Timer0_DisableOC0(void)
{
	CLEAR_BIT(TCCR0_REG,TCCR0_COM01_BIT);
	CLEAR_BIT(TCCR0_REG,TCCR0_COM00_BIT);
}
void Timer1_DisableOC1A(void)
{
	CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A1_BIT);
	CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1A0_BIT);
}
void Timer1_DisableOC1B(void)
{
	CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1B1_BIT);
	CLEAR_BIT(TCCR1A_REG,TCCR1A_COM1B0_BIT);
}
void Timer2_DisableOC2(void)
{
	CLEAR_BIT(TCCR2_REG,TCCR2_COM21_BIT);
	CLEAR_BIT(TCCR2_REG,TCCR2_COM20_BIT);
}